title = "Lionsclub Hilversum"
baseURL = "https://lionshilversum.nl"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
# theme = "ananke"
# themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 4 # this is set low for demonstrating with dummy content. Set to a higher number
# googleAnalytics = "UA-33088611-4"
googleAnalytics = "G-6CDYJ5MZ9M"

enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "https://lionshilversum.nl/favicon.ico"
  description = "We Serve"
  facebook = "https://www.facebook.com/lionshilversum/"
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/IMG_2335.jpg"  # Wilde party outfit
  featured_image = "/images/LionsPannenkoeken.jpg"
  env = "production"
